version: '3.4'

services:
  primo:
    image: ucdlib/primo-devenv
    build: ./
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - type: bind
        source: ./packages
        target: /home/node/primo-explore-devenv/packages
      - type: bind
        source: ./views
        target: /home/node/primo-explore-devenv/primo-explore/custom
    env_file:
      - vars.env
    #command: bash -c "tail -f /dev/null"
    command: [ "/bin/bash", "-c", "node_modules/.bin/gulp run --view 01UCD_INST-UCD --proxy https://search.library.ucdavis.edu:443 --ve" ]